RollNo:-56
Experiment No: 04 Its based on artificial neural network design.

In [17]:
print("Machine learning using deep learning with ANN")

Machine learning using deep learning with ANN


In [ ]:
import numpy as np
input=np.array([[1,0,0],[0,1,0],[0,0,1],[1,1,1]])
input

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 1, 1]])

In [ ]:
output=np.array([[1],[0],[0],[1]])
output

array([[1],
       [0],
       [0],
       [1]])

In [ ]:
weights=np.random.random((3,1))
weights

array([[0.15252156],
       [0.98156801],
       [0.67623399]])

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
s=np.dot(input,weights)
s

array([[0.15252156],
       [0.98156801],
       [0.67623399],
       [1.81032356]])

In [ ]:
def activation (x):
  return (1/(1+np.exp(-x)))
pred=activation(s)
pred

array([[0.53805664],
       [0.72741923],
       [0.66289765],
       [0.85940097]])

In [ ]:
pred= np.round(pred)
pred

array([[1.],
       [1.],
       [1.],
       [1.]])

// apply back propagation to find out error in above predicted value

In [ ]:
def gradient(x):
  return x*(1-x)
s=np.dot(input,weights)+0.2
pred=activation(s)
error=output-pred
value=error*gradient(pred)
weights=weights+np.dot(input.T,value)
error

array([[ 0.41277108],
       [-0.76522962],
       [-0.7060412 ],
       [ 0.11812327]])

In [18]:
for i in range(1000):
  s=np.dot(input,weights)+0.2
  pred=activation(s)
  error=output-pred
  value=error*gradient(pred)
  weights=weights+np.dot(input.T,value)
error

array([[ 2.45956286e-05],
       [-3.37684255e-02],
       [-3.37684254e-02],
       [ 2.91656959e-02]])

In [19]:
pred=np.round(pred)
pred

array([[1.],
       [0.],
       [0.],
       [1.]])

In [20]:
output

array([[1],
       [0],
       [0],
       [1]])