#RollNo:-56
#Experiment No: 04 Its based on artificial neural network design.

In [1]:
print("Machine learning using deep learning with ANN")

Machine learning using deep learning with ANN


In [2]:
import numpy as np
input=np.array([[1,0,0],[0,1,0],[0,0,1],[1,1,1]])
input

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 1, 1]])

In [ ]:
output=np.array([[1],[0],[0],[1]])
output

array([[1],
       [0],
       [0],
       [1]])

In [3]:
weights=np.random.random((3,1))
weights

array([[0.15633486],
       [0.7999134 ],
       [0.95537195]])

In [7]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [10]:
s=np.dot(input,weights)
s

array([[0.15633486],
       [0.7999134 ],
       [0.95537195],
       [1.91162021]])

In [11]:
def activation (x):
  return (1/(1+np.exp(-x)))
pred=activation(s)
pred

array([[0.53900431],
       [0.68995596],
       [0.72219424],
       [0.87120106]])

In [12]:
pred= np.round(pred)
pred

array([[1.],
       [1.],
       [1.],
       [1.]])

// apply back propagation to find out error in above predicted value

In [15]:
def gradient(x):
  return x*(1-x)
s=np.dot(input,weights)+0.2
pred=activation(s)
error=output-pred
value=error*gradient(pred)
weights=weights+np.dot(input.T,value)
error

NameError: ignored

In [14]:
for i in range(1000):
  s=np.dot(input,weights)+0.2
  pred=activation(s)
  error=output-pred
  value=error*gradient(pred)
  weights=weights+np.dot(input.T,value)
error

NameError: ignored

In [ ]:
pred=np.round(pred)
pred

array([[1.],
       [0.],
       [0.],
       [1.]])

In [ ]:
output

array([[1],
       [0],
       [0],
       [1]])